### PR TITLE
Port to GNOME 45

### PR DESCRIPTION
**Pull request by frandieguez**
I have made an initial port to GNOME 45.

It seems to work properly but for that I had to comment one snippet of the code.
Please check the `// TODO: commented because it breaks with a crash` comment. Not sure how to fix it

This port involves 
- Use to the ESM new import formats
- Wrap the extension.js file with the new Extension class and export it by default
- Wrap the prefs.js file to a new ExtensionPreferences class

### CODE REVIEW

**Comment by Vyogami** [comment]
@frandieguez how can i manually compile this to work on gnome 45

any reference or help will be great

**Comment by alk3pInjection** [comment]
> It seems to work properly but for that I had to comment one snippet of the code.

Unfortunately GNOME has deprecated the `get_source()` API. (See also: [mr2311](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2311), [mr2216](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2216))
And consequently, the code commented out won't work as intended even without a crash.

Here is a feasible (not ideal though) [fix](https://github.com/sunwxg/gnome-shell-extension-panelScroll/blob/56b29e4/panelScroll%40sun.wxg%40gmail.com/extension.js#L101) while we're at it.

**Comment by Rmano** [comment]
I am using it, and it works. Thanks @frandieguez.

**Comment by Rmano** [comment]
> @frandieguez how can i manually compile this to work on gnome 45
> 
> any reference or help will be great

@Vyogami  I just cloned [@frandieguez repository](https://github.com/frandieguez/gnome-shell-scroll-workspaces/tree/master), then called `./tools/gup` as per instructions (not sure if needed, though) , then:

1. go to your extension subdirectory: 
    `cd $HOME/.local/share/gnome-shell/extensions`
2. add a symlink to the `scroll-workspaces`  subdirectory:
     `ln -s your-clone-dir/scroll-workspaces scroll-workspaces@gfxmonk.net`
3. log in, log out and then use your preferred method to enable the extension.

HTH...

**Comment by timbertson** [comment]
Many thanks for this PR @frandieguez. The PR as a whole introduces some stuff that doesn't seem necessary, but I've taken the important parts in 4624dd27068f1d42e12e6019f8454bc8f4256ae5.

The good news is the part which broke looks like it isn't needed any more - scroll events on the volume indicator for example never get delivered to this extension, which is what the code originally prevented.

**Comment by Blaimi** [comment]
Hi @timbertson,

I'm happy I got this extension now via the updates from extensions.gnome.org. I use this extension for years now and can't live without it ;-), thanks for all your effort and its gnome 45 port :-).

You mentioned, that scrolling on the top right area should work, e.g. to change the volume. Sadly I cannot confirm this on latest fedora 39. When I scroll over the volume indicator, the volume changes, but so does the workspace :-(.

**Pull request closed without merging**
